interface PartialEmulator {
    name: string;
    args: string[];
    consoles: string[];
}
export const KnownEmulators: {[key: string]: PartialEmulator[]} = { 
    "dolphin": [{ name: "Dolphin", args: ["--exec=%ROM%"], consoles: ["GCN", "Wii"] }],
    "fusion": [
        { name: "Fusion (32x)", args: ["-32x", "-auto", "-fullscreen", "%ROM%"], consoles: ["32x"] },
        { name: "Fusion (Sega CD)", args: ["-scd", "-auto", "-fullscreen", "%ROM%"], consoles: ["SCD"] },
        { name: "Fusion (Game Gear)", args: ["-gg", "-auto", "-fullscreen", "%ROM%"], consoles: ["GG"] },
        { name: "Fusion (Genesis)", args: ["-gen", "-auto", "-fullscreen", "%ROM%"], consoles: ["MD"] },
        { name: "Fusion (Master System)", args: ["-sms", "-auto", "-fullscreen", "%ROM%"], consoles: ["SMS"] }
    ],
    "project64": [{ name: "Project64", args: ["%ROM%"], consoles: ["N64"] }],
    "desmume": [{ name: "DeSmuME", args: ["%ROM%"], consoles: ["NDS"] }],
    "fceux": [{ name: "FCEUX", args: ["%ROM%"], consoles: ["NES"] }],
    "pcsx2": [{ name: "PCSX2", args: ["%ROM%"], consoles: ["PS2"] }],
    "regen": [{ name: "Regen", args: ["--fullscreen", "%ROM%"], consoles: ["SMS", "GG"] }],
    "snes9x": [{ name: "Snes9x", args: ["-fullscreen", "%ROM%"], consoles: ["SNES"] }],
    "visualboyadvance": [{ name: "VisualBoyAdvance", args: ["%ROM%"], consoles: ["GBA", "GBC", "GB"] }],
    "oswan": [{ name: "Oswan", args: ["%ROM%"], consoles: ["WS"] }],
};

export const KnownLibRetroCores: {[key: string]: string[]} = {
    "blastem": ["MD"],
    "bnes": ["NES"],
    "bsnes2014_balanced": ["SNES"],
    "bsnes-mercury": ["SNES"],
    "citra": ["3DS"],
    "desume": ["NDS"],
    "dolphin": ["GCN", "Wii"],
    "duckstation": ["PSX"],
    "fceumm": ["NES"],
    "flycast": ["DC"],
    "gambatte": ["GB", "GBC"],
    "gearboy": ["GB", "GBC"],
    "genesis_plus_gx": ["SMS", "MD", "GG", "SCD"],
    "gpsp": ["GBA"],
    "higan": ["SNES"],
    "kronos": ["Sat"],
    "mednafen_bsnes": ["SNES"],
    "mednafen_cygne": ["WS"],
    "mednafen_psx": ["PSX"],
    "mednafen_psx_hw": ["PSX"],
    "mednafen_saturn": ["Sat"],
    "mednafen_vb": ["VB"],
    "mednafen_vba": ["GBA"],
    "melonds": ["NDS"],
    "mesen": ["NES"],
    "meteor": ["GBA"],
    "mgba": ["GB", "GBC", "GBA"],
    "mupen64plsu": ["N64"],
    "nestopia": ["NES"],
    "nside_balanced": ["SNES"],
    "parallel": ["N64"],
    "pcsx_rearmed": ["PSX"],
    "pcsx2": ["PS2"],
    "picodrive": ["SMS", "MD", "SCD", "32x", "GG"],
    "ppsspp": ["PSP"],
    "quicknes": ["NES"],
    "redream": ["DC"],
    "rustation": ["PSX"],
    "sameboy": ["GB", "GBC"],
    "snes9x": ["SNES"],
    "snes9x_2002": ["SNES"],
    "snes9x_2005": ["SNES"],
    "snes9x_2005_plus": ["SNES"],
    "snes9x_2010": ["SNES"],
    "smsplus": ["SMS"],
    "tempgba": ["GBA"],
    "tgb_dual": ["GB", "GBC"],
    "vba_m": ["GBA"],
    "vba_next": ["GBA"],
    "yabause": ["Sat"]
};